### PR TITLE
fix(db): POST feature to table without sequence

### LINKED ISSUE #171: Bug - cannot POST feature to table without sequence
When a table has been created without a sequence to handle the id, pg_featureserv is unable to create data in this table.

Will not work:
```sql
CREATE TABLE IF NOT EXISTS %s (
			id INT PRIMARY KEY,
			geometry public.geometry(Point, 4326) NOT NULL
);
```

Will be ok:
```sql
CREATE TABLE IF NOT EXISTS %s (
			id SERIAL PRIMARY KEY,
			geometry public.geometry(Point, 4326) NOT NULL
);
```

### PR DESCRIPTION
**Pull request by azarz**
closes #171

I changed the `TestCreateSuperSimpleFeatureDb` in oder to test hte fix (now `mock_ssimple` has no sequence for its id)

### CODE REVIEW

File: internal/api/table.go [hunk 1]
```diff
@@ -41,6 +41,7 @@ type Table struct {
 	DbTypes        map[string]Column
 	JSONTypes      []JSONType
 	ColDesc        []string
+	IDColIsDefault bool
```
Comment (benoitdm-oslandia) [inline internal/api/table.go]:
```suggestion
	IDColHasDefault bool
```
What do you think?

**Review by benoitdm-oslandia — CHANGES_REQUESTED** [review]
May be it is more 'HasDefault' than 'IsDefault'

File: internal/api/table.go (hunk 1 above)
Comment (benoitdm-oslandia) [reply internal/api/table.go]: fixed!

**Review by benoitdm-oslandia — APPROVED** [review]
