### PR TITLE
fix(handler): requested format with Accept header and suffix

### LINKED ISSUE #88: Task - accept header superseds page suffix
even if an user choose to add a suffix (html/json) to a page name, if an accept header is defined then the suffix is ignored. The default behaviour for a web browser is to send an accept header misunderstood by the current code, so user will always retrieve json data when he asked for html ou other.

See also [#41](https://git.oslandia.net/Client-projects/geoplateforme-ign-pg-featureserv/-/merge_requests/41#note_285385)

### PR DESCRIPTION
**Pull request by nick-rv**
Resolves #88

### CODE REVIEW

File: internal/service/handler.go [hunk 1]
```diff
@@ -449,20 +451,25 @@ func handleCollectionItems(w http.ResponseWriter, r *http.Request) *appError {
 	if tbl == nil {
 		return appErrorNotFound(err1, api.ErrMsgCollectionNotFound, name)
 	}
-	param, err := createQueryParams(&reqParam, tbl.Columns, tbl.Srid)
+	param, errQuery := createQueryParams(&reqParam, tbl.Columns, tbl.Srid)
 	if err != nil {
 		return appErrorBadRequest(err, err.Error())
 	}
```
Comment (azarz) [inline internal/service/handler.go]: To remove: `err` is not what is tested here, and `errQuery` is checked line 460

File: internal/service/mock_test/handler_get_test.go [hunk 2]
```diff
@@ -11,6 +11,9 @@ package mock_test
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
+
+ Date     : September 2022
+ Authors  : Nicolas Revelant (nicolas dot revelant at ign dot fr)
```
Comment (azarz) [inline internal/service/mock_test/handler_get_test.go]: Add other authors too.

**Review by azarz — CHANGES_REQUESTED** [review]

File: internal/service/mock_test/handler_get_test.go [hunk 3]
```diff
@@ -43,6 +48,135 @@ func (t *MockTests) TestRoot() {
...
+
+	})
+}
+
+func (t *MockTests) TestGetFormatHeaderAcceptSupersedesSuffix() {
+	t.Test.Run("TestGetFormatHeaderAcceptSupersedesSuffix", func(t *testing.T) {
+
+		htmlAccept := "text/html"
+		checkRouteWithAcceptHeader(t, "/api.json", htmlAccept, http.StatusOK, api.ContentTypeHTML)
+		checkRouteWithAcceptHeader(t, "/api.html", htmlAccept, http.StatusOK, api.ContentTypeHTML)
```
Comment (benoitdm-oslandia) [inline internal/service/mock_test/handler_get_test.go]: we want the opposite: if the user specifies a suffix, it will supersed the header!

File: internal/api/net.go [hunk 4]
```diff
@@ -77,48 +77,59 @@ func RequestedFormat(r *http.Request) string {
...
-		case "txt":
-			return FormatText
-		case "svg":
-			return FormatSVG
-		default:
-			return extension
-		}
-	}
-
 	if hdrAcceptValue != "" {
```
Comment (benoitdm-oslandia) [inline internal/api/net.go]: we want the opposite: if the user specifies a suffix, it will supersed the header!

File: internal/service/handler.go [hunk 5]
```diff
@@ -52,8 +52,10 @@ func InitRouter(basePath string) *mux.Router {
 		Subrouter()
 
 	addRoute(router, "/", handleRoot)
+	addRoute(router, "/home", handleRoot)
```
Comment (benoitdm-oslandia) [inline internal/service/handler.go:57]: is it necessary? It worked well before

File: internal/service/handler.go [hunk 6]
```diff
@@ -449,20 +451,22 @@ func handleCollectionItems(w http.ResponseWriter, r *http.Request) *appError {
 	if tbl == nil {
 		return appErrorNotFound(err1, api.ErrMsgCollectionNotFound, name)
 	}
-	param, err := createQueryParams(&reqParam, tbl.Columns, tbl.Srid)
-	if err != nil {
-		return appErrorBadRequest(err, err.Error())
-	}
+	param, errQuery := createQueryParams(&reqParam, tbl.Columns, tbl.Srid)
 	param.Filter = parseFilter(reqParam.Values, tbl.DbTypes)
```
Comment (benoitdm-oslandia) [inline internal/service/handler.go:455]: must be in the `if errQuery == nil {` block

File: internal/service/mock_test/handler_get_test.go [hunk 7]
```diff
@@ -11,6 +11,11 @@ package mock_test
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
+
+ Date     : September 2022
```
Comment (benoitdm-oslandia) [inline internal/service/mock_test/handler_get_test.go]: this is the creation date not the modification date

**Review by benoitdm-oslandia — CHANGES_REQUESTED** [review]

File: internal/service/mock_test/handler_get_test.go (hunk 3 above)
Comment (nick-rv) [reply internal/service/mock_test/handler_get_test.go]: Ok done

File: internal/service/mock_test/handler_get_test.go (hunk 7 above)
Comment (nick-rv) [reply internal/service/mock_test/handler_get_test.go]: October 2022 according to the following command :
` git log --follow --format=%ad --date default internal/service/mock_test/handler_get_test.go`

File: internal/api/net.go [hunk 8]
```diff
@@ -101,24 +88,41 @@ func RequestedFormat(r *http.Request) string {
 		case "svg":
 			return FormatSVG
 		default:
-			return extension
+			return suffix
```
Comment (benoitdm-oslandia) [inline internal/api/net.go:91]: it will be better to return nil or empty string when we do not understand the suffix

File: internal/api/net.go [hunk 9]
```diff
@@ -101,24 +88,41 @@ func RequestedFormat(r *http.Request) string {
...
+				case ContentTypeSchemaJSON, ContentTypeSchemaPatchJSON:
+					return FormatSchemaJSON
+				case ContentTypeHTML:
+					return FormatHTML
+				case ContentTypeText:
+					return FormatText
+				case ContentTypeSVG:
+					return FormatSVG
+				default:
+					return hdrAcceptValue
```
Comment (benoitdm-oslandia) [inline internal/api/net.go]: as we are in a loop, if we the current `mediaTypeValue` we should `continue` to analyse the other formats. At the end, if nothing is found and we quit the loop, we should return nil or empty string (when we do not understand the format)

File: internal/service/handler.go (hunk 5 above)
Comment (benoitdm-oslandia) [reply internal/service/handler.go:57]: please remove it. We will fix the `.{fmt}` and `{.fmt}` in an other PR

File: internal/service/handler.go [hunk 10]
```diff
@@ -52,9 +53,13 @@ func InitRouter(basePath string) *mux.Router {
...
 
 	addRoute(router, "/", handleRoot)
-	addRoute(router, "/home{.fmt}", handleRoot)
+
+	addRoute(router, "/home", handleRoot)
+	addRoute(router, "/home.{fmt}", handleRoot)
+
 	// consistent with pg_tileserv
-	addRoute(router, "/index{.fmt}", handleRoot)
+	addRoute(router, "/index", handleRoot)
```
Comment (benoitdm-oslandia) [inline internal/service/handler.go:61]: please remove it. We will fix the `.{fmt}` and `{.fmt}` in an other PR

File: internal/service/util.go [hunk 11]
```diff
@@ -190,11 +190,17 @@ func serveURLBase(r *http.Request) string {
...
 
-func getRequestVar(varname string, r *http.Request) string {
+// Return value for the requested path route variable
+func getRequestVar(varName string, r *http.Request) string {
 	vars := mux.Vars(r)
-	nameFull := vars[varname]
-	name := api.PathStripFormat(nameFull)
-	return name
+	return vars[varName]
+}
```
Comment (benoitdm-oslandia) [inline internal/service/util.go:197]: is it still used? or can we remove it?

**Review by benoitdm-oslandia — CHANGES_REQUESTED** [review]

File: internal/api/net.go (hunk 8 above)
Comment (nick-rv) [reply internal/api/net.go:91]: The reason is the the format value is used by the handler functions, into the error message when the format value is not supported/unrecognized : 
`			return appErrorNotAcceptable(nil, api.ErrMsgNotSupportedFormat, format)`

File: internal/api/net.go (hunk 9 above)
Comment (nick-rv) [reply internal/api/net.go]: The reason is the the format value is used by the handler functions, into the error message when the format value is not supported/unrecognized : 
`			return appErrorNotAcceptable(nil, api.ErrMsgNotSupportedFormat, format)`

File: internal/service/util.go (hunk 11 above)
Comment (nick-rv) [reply internal/service/util.go:197]: `func getRequestVar(varName string, r *http.Request)` is now used to get a parameter value inside the URL elements
`func getRequestVarStrip(varName string, r *http.Request)` is dedicated to get a value from a parameter situated at the end of the URL (stripping the possible suffix)

File: internal/api/net.go (hunk 9 above)
Comment (nick-rv) [reply internal/api/net.go]: OK, hdrAcceptValue is now returned outside the for loop, once all formats have been checked.

**Review by benoitdm-oslandia — APPROVED** [review]
you can merge

**Review by azarz — APPROVED** [review]
